[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "npm cache clean --force",
  "rm -rf node_modules",
  "npm install"
]

[phases.build]
cmds = ["NODE_ENV=production npm run build:preview"]

[start]
cmd = "npx serve dist -p ${PORT:-3000}"

[variables]
NODE_ENV = "production" 