[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "npm install"
]

[phases.build]
cmds = [
  "echo 'NODE_ENV=production' > env.local",
  "echo 'VITE_MEDUSA_BASE=$VITE_MEDUSA_BASE' >> env.local",
  "echo 'VITE_MEDUSA_BACKEND_URL=$VITE_MEDUSA_BACKEND_URL' >> env.local",
  "echo 'VITE_PUBLISHABLE_API_KEY=$VITE_PUBLISHABLE_API_KEY' >> env.local",
  "echo 'VITE_TALK_JS_APP_ID=$VITE_TALK_JS_APP_ID' >> env.local",
  "echo 'VITE_DISABLE_SELLERS_REGISTRATION=$VITE_DISABLE_SELLERS_REGISTRATION' >> env.local",
  "npm run build:preview"
]

[variables]
NODE_ENV = "production"
