[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "npm cache clean --force",
  "rm -rf node_modules",
  "npm install"
]

[phases.build]
cmds = ["NODE_ENV=production npm run build:preview"]


[variables]
NODE_ENV = "production" 