[build]
command = "yarn install && NODE_ENV=production yarn build:preview"
output = "dist"

[serve]
directory = "dist"
port = 3000
spa = true
gzip = true
brotli = true

[headers]
"/*" = [
  "Cache-Control: public, max-age=0, must-revalidate"
]

"/*.{js,css,svg}" = [
  "Cache-Control: public, max-age=31536000, immutable"
]

[redirects]
from = "/*"
to = "/index.html"
status = 200 